# Generated by Django 5.0.2 on 2025-11-16 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_login', 'Connexion utilisateur'), ('user_logout', 'Déconnexion utilisateur'), ('user_register', 'Inscription utilisateur'), ('user_update', 'Modification utilisateur'), ('user_delete', 'Suppression utilisateur'), ('ticket_create', 'Création ticket'), ('ticket_confirm', 'Confirmation ticket'), ('ticket_cancel', 'Annulation ticket'), ('ticket_scan', 'Scan ticket'), ('payment_init', 'Initialisation paiement'), ('payment_success', 'Paiement réussi'), ('payment_failed', 'Paiement échoué'), ('payment_refund', 'Remboursement'), ('trip_create', 'Création voyage'), ('trip_update', 'Modification voyage'), ('trip_delete', 'Suppression voyage'), ('trip_cancel', 'Annulation voyage'), ('company_create', 'Création compagnie'), ('company_approve', 'Approbation compagnie'), ('company_reject', 'Rejet compagnie'), ('company_suspend', 'Suspension compagnie'), ('admin_action', 'Action admin')], db_index=True, max_length=50, verbose_name='action')),
                ('description', models.TextField(verbose_name='description')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='détails')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name="type d'objet")),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='ID objet')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Avertissement'), ('error', 'Erreur'), ('critical', 'Critique')], db_index=True, default='info', max_length=20, verbose_name='sévérité')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='tags')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': "log d'activité",
                'verbose_name_plural': "logs d'activité",
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'action', 'created_at'], name='activity_lo_user_id_9a0a50_idx'), models.Index(fields=['action', 'created_at'], name='activity_lo_action_0f3584_idx'), models.Index(fields=['severity', 'created_at'], name='activity_lo_severit_5f4b9b_idx'), models.Index(fields=['ip_address', 'created_at'], name='activity_lo_ip_addr_4fb53a_idx'), models.Index(fields=['object_id', 'content_type'], name='activity_lo_object__3f6e93_idx')],
            },
        ),
    ]
