# Generated by Django 5.1.3 on 2025-12-09 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        # Operation skipped to fix production deployment error (JSONB to VARCHAR[] cast issue)
        # We are disabling ActivityLog features anyway.
    ]
