# Generated by Django 5.0.2 on 2025-11-16 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='message')),
                ('is_internal', models.BooleanField(default=False, help_text='Message visible uniquement par les admins', verbose_name='interne')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='claims/messages/%Y/%m/', verbose_name='pièce jointe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
            ],
            options={
                'verbose_name': 'message réclamation',
                'verbose_name_plural': 'messages réclamation',
                'db_table': 'claim_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('payment_issue', 'Problème de paiement'), ('booking_issue', 'Problème de réservation'), ('service_quality', 'Qualité de service'), ('refund_request', 'Demande de remboursement'), ('technical_issue', 'Problème technique'), ('complaint', 'Plainte'), ('other', 'Autre')], db_index=True, max_length=50, verbose_name='catégorie')),
                ('subject', models.CharField(max_length=255, verbose_name='sujet')),
                ('description', models.TextField(verbose_name='description')),
                ('attachment_1', models.FileField(blank=True, null=True, upload_to='claims/attachments/%Y/%m/', verbose_name='pièce jointe 1')),
                ('attachment_2', models.FileField(blank=True, null=True, upload_to='claims/attachments/%Y/%m/', verbose_name='pièce jointe 2')),
                ('attachment_3', models.FileField(blank=True, null=True, upload_to='claims/attachments/%Y/%m/', verbose_name='pièce jointe 3')),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('in_progress', 'En cours'), ('resolved', 'Résolue'), ('closed', 'Fermée'), ('rejected', 'Rejetée')], db_index=True, default='open', max_length=20, verbose_name='statut')),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('urgent', 'Urgente')], db_index=True, default='medium', max_length=20, verbose_name='priorité')),
                ('admin_response', models.TextField(blank=True, verbose_name='réponse admin')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='notes de résolution')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifiée le')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='résolue le')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='fermée le')),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_claims', to=settings.AUTH_USER_MODEL, verbose_name='assignée à')),
            ],
            options={
                'verbose_name': 'réclamation',
                'verbose_name_plural': 'réclamations',
                'db_table': 'claims',
                'ordering': ['-created_at'],
            },
        ),
    ]
