# Generated by Django 5.0.2 on 2025-11-16 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0002_initial'),
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='trips.trip', verbose_name='voyage'),
        ),
        migrations.AddField(
            model_name='claim',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AddField(
            model_name='claimmessage',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='claims.claim', verbose_name='réclamation'),
        ),
        migrations.AddField(
            model_name='claimmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_messages', to=settings.AUTH_USER_MODEL, verbose_name='expéditeur'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['user', 'status'], name='claims_user_id_7db873_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['status', 'priority'], name='claims_status_296f44_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['category', 'status'], name='claims_categor_f7c514_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['assigned_to', 'status'], name='claims_assigne_239a06_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['created_at'], name='claims_created_ba390a_idx'),
        ),
    ]
