# Generated by Django 5.0.2 on 2025-11-16 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In-app'), ('push', 'Push')], db_index=True, max_length=20, verbose_name='type')),
                ('category', models.CharField(choices=[('booking_confirmation', 'Confirmation réservation'), ('payment_success', 'Paiement réussi'), ('payment_failed', 'Paiement échoué'), ('trip_reminder', 'Rappel voyage'), ('trip_cancelled', 'Voyage annulé'), ('refund_processed', 'Remboursement traité'), ('account_verification', 'Vérification compte'), ('password_reset', 'Réinitialisation mot de passe'), ('company_approved', 'Compagnie approuvée'), ('company_rejected', 'Compagnie rejetée'), ('general', 'Général')], db_index=True, default='general', max_length=50, verbose_name='catégorie')),
                ('title', models.CharField(max_length=255, verbose_name='titre')),
                ('message', models.TextField(verbose_name='message')),
                ('html_content', models.TextField(blank=True, verbose_name='contenu HTML')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Données additionnelles liées à la notification', verbose_name='métadonnées')),
                ('action_url', models.URLField(blank=True, max_length=500, verbose_name="URL d'action")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('failed', 'Échoué'), ('read', 'Lu')], db_index=True, default='pending', max_length=20, verbose_name='statut')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, verbose_name='email destinataire')),
                ('recipient_phone', models.CharField(blank=True, max_length=17, verbose_name='téléphone destinataire')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='envoyé le')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='lu le')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='tentatives')),
                ('max_attempts', models.PositiveIntegerField(default=3, verbose_name='tentatives max')),
                ('error_message', models.TextField(blank=True, verbose_name="message d'erreur")),
                ('scheduled_at', models.DateTimeField(blank=True, help_text="Date/heure d'envoi planifié", null=True, verbose_name='planifié pour')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='notificatio_user_id_8ab96f_idx'), models.Index(fields=['notification_type', 'status'], name='notificatio_notific_21f913_idx'), models.Index(fields=['category', 'status'], name='notificatio_categor_a693df_idx'), models.Index(fields=['status', 'scheduled_at'], name='notificatio_status_2ea0f1_idx'), models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx')],
            },
        ),
    ]
