# Generated by Django 5.0.2 on 2025-11-16 14:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('image', models.ImageField(upload_to='banners/%Y/%m/', verbose_name='image')),
                ('link_url', models.URLField(blank=True, max_length=500, verbose_name='URL du lien')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('start_date', models.DateTimeField(verbose_name='date début')),
                ('end_date', models.DateTimeField(verbose_name='date fin')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('target_role', models.CharField(blank=True, help_text='Laisser vide pour tous les utilisateurs', max_length=20, verbose_name='rôle ciblé')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='vues')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='clics')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifiée le')),
            ],
            options={
                'verbose_name': 'bannière',
                'verbose_name_plural': 'bannières',
                'db_table': 'banners',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', 'Général'), ('booking', 'Réservation'), ('payment', 'Paiement'), ('cancellation', 'Annulation'), ('account', 'Compte')], db_index=True, max_length=50, verbose_name='catégorie')),
                ('question', models.TextField(verbose_name='question')),
                ('answer', models.TextField(verbose_name='réponse')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='vues')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifiée le')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'db_table': 'faqs',
                'ordering': ['category', 'order', '-views'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_commission_rate', models.DecimalField(decimal_places=2, default=5.0, help_text='Pourcentage de commission (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='taux de commission par défaut')),
                ('ticket_cancellation_deadline_hours', models.PositiveIntegerField(default=24, help_text="Nombre d'heures avant le départ pour annuler un ticket", verbose_name='délai annulation ticket (heures)')),
                ('send_email_notifications', models.BooleanField(default=True, verbose_name='envoyer notifications email')),
                ('send_sms_notifications', models.BooleanField(default=True, verbose_name='envoyer notifications SMS')),
                ('trip_reminder_hours_before', models.PositiveIntegerField(default=24, help_text='Envoyer un rappel X heures avant le départ', verbose_name='rappel voyage (heures avant)')),
                ('payment_timeout_minutes', models.PositiveIntegerField(default=15, help_text="Durée de validité d'une transaction de paiement", verbose_name='timeout paiement (minutes)')),
                ('min_ticket_price', models.DecimalField(decimal_places=2, default=500.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix minimum ticket')),
                ('max_ticket_price', models.DecimalField(decimal_places=2, default=100000.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix maximum ticket')),
                ('qr_code_expiration_hours', models.PositiveIntegerField(default=24, help_text='Durée de validité du QR code après le départ', verbose_name='expiration QR code (heures)')),
                ('max_tickets_per_booking', models.PositiveIntegerField(default=10, verbose_name='tickets max par réservation')),
                ('allow_overbooking', models.BooleanField(default=False, verbose_name='autoriser surréservation')),
                ('overbooking_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='pourcentage surréservation')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='mode maintenance')),
                ('maintenance_message', models.TextField(blank=True, default='La plateforme est actuellement en maintenance. Veuillez réessayer plus tard.', verbose_name='message maintenance')),
                ('support_email', models.EmailField(default='support@ticketzen.com', max_length=254, verbose_name='email support')),
                ('support_phone', models.CharField(default='+225XXXXXXXXXX', max_length=17, verbose_name='téléphone support')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updates', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
            ],
            options={
                'verbose_name': 'paramètres plateforme',
                'verbose_name_plural': 'paramètres plateforme',
                'db_table': 'platform_settings',
            },
        ),
    ]
