# Generated by Django 5.0.2 on 2025-11-16 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardingPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_status', models.CharField(choices=[('valid', 'Valide'), ('invalid', 'Invalide'), ('already_used', 'Déjà utilisé'), ('expired', 'Expiré'), ('wrong_trip', 'Mauvais voyage')], db_index=True, default='valid', max_length=20, verbose_name='statut scan')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='scanné le')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('device_info', models.JSONField(blank=True, default=dict, help_text="Informations sur l'appareil mobile utilisé", verbose_name='info appareil')),
                ('is_offline_scan', models.BooleanField(default=False, help_text='Scan effectué en mode hors ligne', verbose_name='scan hors ligne')),
                ('synced_at', models.DateTimeField(blank=True, help_text='Date de synchronisation si scan offline', null=True, verbose_name='synchronisé le')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('boarding_agent', models.ForeignKey(limit_choices_to={'role': 'embarqueur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boarded_passes', to=settings.AUTH_USER_MODEL, verbose_name='embarqueur')),
            ],
            options={
                'verbose_name': 'pass embarquement',
                'verbose_name_plural': 'passes embarquement',
                'db_table': 'boarding_passes',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
