# Generated by Django 5.0.2 on 2025-11-16 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boarding', '0002_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardingpass',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boarding_passes', to='trips.trip', verbose_name='voyage'),
        ),
        migrations.AddIndex(
            model_name='boardingpass',
            index=models.Index(fields=['ticket', 'trip'], name='boarding_pa_ticket__9c9a38_idx'),
        ),
        migrations.AddIndex(
            model_name='boardingpass',
            index=models.Index(fields=['boarding_agent', 'scanned_at'], name='boarding_pa_boardin_cd8bfe_idx'),
        ),
        migrations.AddIndex(
            model_name='boardingpass',
            index=models.Index(fields=['scan_status'], name='boarding_pa_scan_st_ce2380_idx'),
        ),
        migrations.AddIndex(
            model_name='boardingpass',
            index=models.Index(fields=['is_offline_scan', 'synced_at'], name='boarding_pa_is_offl_172e4e_idx'),
        ),
    ]
