# Generated by Django 5.0.2 on 2025-11-16 14:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('bus', 'Bus'), ('minibus', 'Minibus'), ('van', 'Van'), ('car', 'Voiture')], default='bus', max_length=20, verbose_name='type de véhicule')),
                ('registration_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name="numéro d'immatriculation")),
                ('brand', models.CharField(max_length=100, verbose_name='marque')),
                ('model', models.CharField(max_length=100, verbose_name='modèle')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1990)], verbose_name='année')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='couleur')),
                ('total_seats', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='nombre de places')),
                ('seat_configuration', models.JSONField(blank=True, default=dict, help_text='Configuration JSON des sièges avec numéros et types', verbose_name='configuration des sièges')),
                ('has_ac', models.BooleanField(default=True, verbose_name='climatisation')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='WiFi')),
                ('has_tv', models.BooleanField(default=False, verbose_name='TV')),
                ('has_usb_ports', models.BooleanField(default=False, verbose_name='ports USB')),
                ('has_toilet', models.BooleanField(default=False, verbose_name='toilettes')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('maintenance', 'En maintenance'), ('inactive', 'Inactif')], db_index=True, default='active', max_length=20, verbose_name='statut')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('photo_main', models.ImageField(blank=True, null=True, upload_to='vehicles/photos/%Y/%m/', verbose_name='photo principale')),
                ('photo_interior', models.ImageField(blank=True, null=True, upload_to='vehicles/photos/%Y/%m/', verbose_name='photo intérieur')),
                ('insurance_expiry', models.DateField(blank=True, null=True, verbose_name='expiration assurance')),
                ('technical_inspection_expiry', models.DateField(blank=True, null=True, verbose_name='expiration visite technique')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='dernière maintenance')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='prochaine maintenance')),
                ('maintenance_notes', models.TextField(blank=True, verbose_name='notes de maintenance')),
                ('total_trips', models.PositiveIntegerField(default=0, verbose_name='total voyages')),
                ('total_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='kilométrage total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='companies.company', verbose_name='compagnie')),
            ],
            options={
                'verbose_name': 'véhicule',
                'verbose_name_plural': 'véhicules',
                'db_table': 'vehicles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='vehicles_company_bd8720_idx'), models.Index(fields=['registration_number'], name='vehicles_registr_eb8990_idx'), models.Index(fields=['vehicle_type', 'status'], name='vehicles_vehicle_7251c0_idx')],
            },
        ),
    ]
