# Generated by Django 5.0.2 on 2025-11-16 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('registration_number', models.CharField(db_index=True, max_length=100, unique=True, verbose_name="numéro d'enregistrement")),
                ('tax_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='identifiant fiscal')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('phone_number', models.CharField(max_length=17, verbose_name='téléphone')),
                ('address', models.TextField(verbose_name='adresse')),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='ville')),
                ('country', models.CharField(default="Côte d'Ivoire", max_length=100, verbose_name='pays')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/%Y/%m/', verbose_name='logo')),
                ('license_document', models.FileField(blank=True, null=True, upload_to='companies/documents/%Y/%m/', verbose_name='licence de transport')),
                ('insurance_document', models.FileField(blank=True, null=True, upload_to='companies/documents/%Y/%m/', verbose_name='assurance')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée'), ('suspended', 'Suspendue')], db_index=True, default='pending', max_length=20, verbose_name='statut')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('admin_notes', models.TextField(blank=True, help_text='Notes internes visibles uniquement par les admins', verbose_name='notes admin')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='validée le')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=5.0, help_text='Pourcentage de commission (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='taux de commission')),
                ('total_trips', models.PositiveIntegerField(default=0, verbose_name='total voyages')),
                ('total_tickets_sold', models.PositiveIntegerField(default=0, verbose_name='total tickets vendus')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='revenu total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifiée le')),
            ],
            options={
                'verbose_name': 'compagnie',
                'verbose_name_plural': 'compagnies',
                'db_table': 'companies',
                'ordering': ['-created_at'],
            },
        ),
    ]
