# Generated by Django 5.0.2 on 2025-11-16 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_companies', to=settings.AUTH_USER_MODEL, verbose_name='validée par'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['status', 'is_active'], name='companies_status_53a67b_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['city', 'is_active'], name='companies_city_35c0e7_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['slug'], name='companies_slug_e0676c_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['registration_number'], name='companies_registr_49a0dd_idx'),
        ),
    ]
