# Generated by Django 5.0.2 on 2025-11-16 14:03

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(db_index=True, editable=False, max_length=100, unique=True, verbose_name='ID transaction')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='montant')),
                ('platform_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='commission plateforme')),
                ('company_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='montant compagnie')),
                ('payment_method', models.CharField(choices=[('orange_money', 'Orange Money'), ('mtn_money', 'MTN Money'), ('moov_money', 'Moov Money'), ('wave', 'Wave'), ('visa', 'Visa'), ('mastercard', 'Mastercard')], db_index=True, max_length=20, verbose_name='méthode de paiement')),
                ('phone_number', models.CharField(blank=True, help_text='Pour mobile money', max_length=17, verbose_name='numéro de téléphone')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('success', 'Réussi'), ('failed', 'Échoué'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], db_index=True, default='pending', max_length=20, verbose_name='statut')),
                ('provider_transaction_id', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='ID transaction provider')),
                ('provider_response', models.JSONField(blank=True, default=dict, verbose_name='réponse provider')),
                ('payment_url', models.URLField(blank=True, max_length=500, verbose_name='URL de paiement')),
                ('refund_transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID transaction remboursement')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='montant remboursé')),
                ('refund_reason', models.TextField(blank=True, verbose_name='raison remboursement')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='remboursé le')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='complété le')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='companies.company', verbose_name='compagnie')),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
