# Generated by Django 5.0.2 on 2025-11-16 14:03

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(db_index=True, editable=False, max_length=20, unique=True, verbose_name='numéro de ticket')),
                ('passenger_first_name', models.CharField(max_length=150, verbose_name='prénom passager')),
                ('passenger_last_name', models.CharField(max_length=150, verbose_name='nom passager')),
                ('passenger_phone', models.CharField(max_length=17, verbose_name='téléphone passager')),
                ('passenger_email', models.EmailField(max_length=254, verbose_name='email passager')),
                ('passenger_id_number', models.CharField(blank=True, max_length=50, verbose_name='numéro CNI/Passport')),
                ('seat_number', models.CharField(db_index=True, max_length=10, verbose_name='numéro de siège')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='prix')),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='frais plateforme')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant total')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('cancelled', 'Annulé'), ('used', 'Utilisé'), ('expired', 'Expiré'), ('refunded', 'Remboursé')], db_index=True, default='pending', max_length=20, verbose_name='statut')),
                ('is_paid', models.BooleanField(db_index=True, default=False, verbose_name='payé')),
                ('qr_code', models.TextField(blank=True, verbose_name='QR code')),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='tickets/qr_codes/%Y/%m/', verbose_name='image QR code')),
                ('boarding_time', models.DateTimeField(blank=True, null=True, verbose_name='heure embarquement')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='annulé le')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='raison annulation')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='montant remboursé')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmé le')),
                ('boarded_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'embarqueur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boarded_tickets', to=settings.AUTH_USER_MODEL, verbose_name='embarqué par')),
                ('passenger', models.ForeignKey(limit_choices_to={'role': 'voyageur'}, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='passager')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket', to='payments.payment', verbose_name='paiement')),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
                'db_table': 'tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
