# Generated by Django 5.0.2 on 2025-11-16 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='trips.trip', verbose_name='voyage'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_number'], name='tickets_ticket__4c9624_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['trip', 'status'], name='tickets_trip_id_06a234_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['passenger', 'status'], name='tickets_passeng_ba82f4_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'is_paid'], name='tickets_status_a59e36_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['trip', 'seat_number'], name='tickets_trip_id_c0fad2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('trip', 'seat_number')},
        ),
    ]
