# Generated by Django 5.0.2 on 2025-11-16 14:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_initial'),
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('country', models.CharField(default="Côte d'Ivoire", max_length=100, verbose_name='pays')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifiée le')),
            ],
            options={
                'verbose_name': 'ville',
                'verbose_name_plural': 'villes',
                'db_table': 'cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_location', models.CharField(help_text='Gare routière, adresse précise', max_length=255, verbose_name='lieu de départ')),
                ('arrival_location', models.CharField(help_text='Gare routière, adresse précise', max_length=255, verbose_name="lieu d'arrivée")),
                ('departure_datetime', models.DateTimeField(db_index=True, verbose_name='date/heure de départ')),
                ('estimated_arrival_datetime', models.DateTimeField(verbose_name='arrivée estimée')),
                ('actual_departure_datetime', models.DateTimeField(blank=True, null=True, verbose_name='départ réel')),
                ('actual_arrival_datetime', models.DateTimeField(blank=True, null=True, verbose_name='arrivée réelle')),
                ('estimated_duration', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='durée estimée (minutes)')),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='distance (km)')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='prix de base')),
                ('total_seats', models.PositiveIntegerField(verbose_name='places totales')),
                ('available_seats', models.PositiveIntegerField(verbose_name='places disponibles')),
                ('reserved_seats', models.PositiveIntegerField(default=0, verbose_name='places réservées')),
                ('status', models.CharField(choices=[('scheduled', 'Programmé'), ('boarding', 'Embarquement'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], db_index=True, default='scheduled', max_length=20, verbose_name='statut')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='actif')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='récurrent')),
                ('allows_cancellation', models.BooleanField(default=True, verbose_name='annulation autorisée')),
                ('cancellation_deadline_hours', models.PositiveIntegerField(default=24, help_text="Nombre d'heures avant le départ pour annuler", verbose_name='délai annulation (heures)')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('driver_notes', models.TextField(blank=True, verbose_name='notes chauffeur')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='revenu total')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='montant commission')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('arrival_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrivals', to='trips.city', verbose_name="ville d'arrivée")),
                ('boarding_agents', models.ManyToManyField(blank=True, limit_choices_to={'role': 'embarqueur'}, related_name='assigned_trips', to=settings.AUTH_USER_MODEL, verbose_name='embarqueurs')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='companies.company', verbose_name='compagnie')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trips', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('departure_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departures', to='trips.city', verbose_name='ville de départ')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='fleet.vehicle', verbose_name='véhicule')),
            ],
            options={
                'verbose_name': 'voyage',
                'verbose_name_plural': 'voyages',
                'db_table': 'trips',
                'ordering': ['departure_datetime'],
                'indexes': [models.Index(fields=['departure_city', 'arrival_city', 'departure_datetime'], name='trips_departu_186713_idx'), models.Index(fields=['company', 'status'], name='trips_company_1b3206_idx'), models.Index(fields=['departure_datetime', 'status'], name='trips_departu_f567d9_idx'), models.Index(fields=['status', 'is_active'], name='trips_status_efd117_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(check=models.Q(('available_seats__lte', models.F('total_seats'))), name='available_seats_not_exceed_total'),
        ),
    ]
